### ISSUE TITLE
Change directory structure to match CoreMedia 10 extension mechanism

### ISSUE THREAD

**Issue by mtommila** [CoreMedia/coremedia-globallink-connect-integration#27]
The current directory structure of the connector (everything being under `modules/extensions`) is from CoreMedia 9 and the recommended directory structure for extensions was changed in CoreMedia 10. In other words, extensions for each app are now under the `apps` directory, below each app in a subdirectory `modules/extensions`.

Please change the directory structure to match the CoreMedia 10 recommendations.

For example:
```
modules/extensions/apps/workflow-server/pom.xml -> apps/workflow-server/modules/extensions/gcc/pom.xml
modules/extensions/apps/workflow-server/gcc-workflow-server/pom.xml -> apps/workflow-server/modules/extensions/gcc/gcc-workflow-server/pom.xml
modules/extensions/apps/workflow-server/gcc-workflow-server-facade/gcc-restclient-facade-default/pom.xml -> apps/workflow-server/modules/extensions/gcc/gcc-workflow-server-facade/gcc-restclient-facade-default/pom.xml
modules/extensions/apps/workflow-server/gcc-workflow-server-facade/gcc-restclient-facade-disabled/pom.xml -> apps/workflow-server/modules/extensions/gcc/gcc-workflow-server-facade/gcc-restclient-facade-disabled/pom.xml
modules/extensions/apps/workflow-server/gcc-workflow-server-facade/gcc-restclient-facade-mock/pom.xml -> apps/workflow-server/modules/extensions/gcc/gcc-workflow-server-facade/gcc-restclient-facade-mock/pom.xml
modules/extensions/apps/workflow-server/gcc-workflow-server-facade/gcc-restclient-facade/pom.xml -> apps/workflow-server/modules/extensions/gcc/gcc-workflow-server-facade/gcc-restclient-facade/pom.xml
modules/extensions/apps/workflow-server/gcc-workflow-server-util/pom.xml -> apps/workflow-server/modules/extensions/gcc/gcc-workflow-server-util/pom.xml
```

**Comment by aprantl** [comment]
Even in CMCCv10, putting all files into "modules/extensions" for externally provided extension is still the way to go. The extension tool in the Blueprint workspace is then responsible to add the extension's modules to the corresponding POMs in the apps. One reason for this is that you can integrate the extension by only adding one git submodule. 
If you plan to heavily customize the integration, so that updating becomes difficult anyway, you can also add the modules directly to the apps.
